### ISSUE TITLE
Del is huge since v4.1.1

### ISSUE THREAD

**Issue by nikku** [sindresorhus/del#111]
![image](https://user-images.githubusercontent.com/58601/63772433-5de11000-c8d9-11e9-8fee-f876c59098c8.png)

Cf. [packagephobia](https://packagephobia.now.sh/result?p=del).

As a user I do not quite understand why I need to download 1.4 MBytes for the utility.

**Comment by sindresorhus** [comment]
> As a user I do not quite understand why I need to download 1.4 MBytes for the utility.

You could have easily checked this yourself though:

<img width="415" alt="Screenshot 2019-08-28 at 02 17 31" src="https://user-images.githubusercontent.com/170270/63816848-f9a26880-c939-11e9-864b-f98e21784178.png">

The size is not caused by `del`, but rather its dependencies, which are out of our control.

When https://github.com/sindresorhus/globby/issues/109 is resolved, the size will be half.

We cannot really do much about the `fast-glob` size. You could open an issue about that there: https://github.com/mrmlnc/fast-glob

**Comment by Schweinepriester** [comment]
sindresorhus/globby#109 is resolved, might now be the time for a slimmer version? :)
