### ISSUE TITLE
Error: EPERM - rmdir

### ISSUE THREAD

**Issue by iongion** [sindresorhus/del#39]
On rare occasions I get this:
```
[11:40:41] 'clean.build' errored after 412 ms
[11:40:41] Error: EPERM, rmdir 'W:\Workspace\my-project\build'
    at Error (native)
```
It happens on OSX too, but never got it on Linux

**Comment by sindresorhus** [comment]
It means you don't have permission to delete the at folder. It might have been created using another user or super user. https://www.google.co.th/search?q=Error%3A+EPERM&oq=Error%3A+EPERM&aqs=chrome..69i57j69i58j69i61.279j0j1&sourceid=chrome&es_sm=91&ie=UTF-8

**Comment by iongion** [comment]
No, it does not mean that, but thank you for the link!

**Comment by sindresorhus** [comment]
@iongion What's to understand? You've given me nothing to work with other an a generic error message that you could have easily Googled for yourself. I gave you as much time as put into this issue. Also realize I get hundreds of these kinds of issues every week, and almost all of them are some kind of user mistake or problem with their system.

**Comment by iongion** [comment]
I have updated the module to 2.0.0, it seems not to happen anymore, the debate is long over the webs, some blame NTFS as being the source of errors(having it occur on OSX shows it might not be file-system related). I just thought you met this before and in that respect I have posted it. I am sorry for creating you anger, I thought that the whole idea with public contributions is that people help each-other. Do you think I can have a better understanding of what happens behind the scenes of this code than you ?
```
del('build/**/*.json')
```

I am an user of your project, I chosen it because it solves a problem I face everyday, because I do no want to roll my own, that is why I trust all that in to the developer's hands. When issues appear because of introducing this, what do you expect your users to do ?

I am not just jumping into reporting bugs, make sure I did my research first.
In all good will and honesty, how would you have expected this to be reported ?
Or why/what rational process should have brought me to the decisions not to open this ticket at all ?

**Comment by kevva** [comment]
Looking at your issue and the absence of any code or details about your enviroment etc, there no way to draw any other conclusions than you having a permission issue (which `EPERM` is).

**Comment by sindresorhus** [comment]
> I am sorry for creating you anger

**Comment by sindresorhus** [comment]
> I am sorry for creating you anger

I'm not sure why you would think I'm angry, I'm not at all. Just telling why I responded like I did :)

> I thought that the whole idea with public contributions is that people help each-other.

Usually it's people demanding me to help them.

> When issues appear because of introducing this, what do you expect your users to do?

At minimum, Google the error message and do some light debugging yourself.

> In all good will and honesty, how would you have expected this to be reported?

Include which version of `del` you're using, Node.js version, a snippet of code that can reproduce the issue.

> Or why/what rational process should have brought me to the decisions not to open this ticket at all ?

I'm not saying you shouldn't have opened this issue. I'm just saying there's not much I can do about it based on the info you provided, and it's most likely an issue out of my hands. I have no way to reproduce it, so how do you expect me to fix anything?

I've looked into this for you, and it seems like this might be relevant: https://github.com/isaacs/rimraf/issues/86 And it might be fixed by doing retries on EPERM, as the EPERM might only be temporary. `rimraf
