### ISSUE TITLE
del 5.0.0 not finding files in Windows

### ISSUE THREAD

**Issue by aarongoldenthal** [sindresorhus/del#93]
System configuration:
- Windows 10 version 1809
- Node: v12.5.0

I upgraded a project today from del 4.1.1 to 5.0.0 and noticed that no files were being deleted with the following:
```js
    const testDir = './tests/test-cases';
    del.sync([path.join(testDir, '*.html')]);
```

This has previously run nominally on both Windows and Linux.  I tried using dry run with various options and no files were identified.  I ultimately tried

```js
    del.sync([path.join(process.cwd(), '**')], {dryRun: true});
```

to find anything, but it returned no files (although there are 12680 files).

I ran the same code on Linux in Node Docker containers, both latest (Node: v12.5.0), and LTS (Node v10.16.0), and everything was nominal (files deleted as expected, dry run showed expected files).

**Comment by sindresorhus** [comment]
Glob patterns can now only contain forward-slashes, not backward-slashes, so if you want to construct a glob pattern from path components, you need to use `path.posix.join()` instead of `path.join()`.

This change is because of a change in `fast-glob` to allow escaping glob patterns: https://github.com/mrmlnc/fast-glob/releases/tag/3.0.0

**Comment by electerious** [comment]
That's something that could be added to the release notes as a help for those who upgrade. I think several people will run into the backward-slashes problem.

**Comment by sindresorhus** [comment]
It is in the release notes.
